version: '3.9'

services:
    prisma-react:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        image: faisalfjri/prisma-next
        container_name: prisma-next
        ports:
            - 3006:3006
        restart: always
        networks:
            - shared_network

networks:
    shared_network:
        driver: bridge
        name: shared_network
